services:
  mysql:
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  openemr:
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - ../:/var/www/localhost/htdocs/openemr
    environment:
      FORCE_NO_BUILD_MODE: "yes"
      EMPTY: "yes"
